// Generated by AppApprove. Overwritten on every deploy by the
// "Generate build metadata" step in .github/workflows/deploy.yml. Do
// not edit by hand — your changes will be lost on the next push.

export const BUILD_VERSION = "0.1.0";
export const BUILD_GIT_SHA = "unknown";
export const BUILD_TIMESTAMP = "2026-05-15T20:45:17.601Z";
export const DEPENDENCIES = {
  "@shopify/polaris": "^13.9.0",
  "@shopify/shopify-app-remix": "^3.7.0",
  "@shopify/ui-extensions-react": "^2025.7.0"
} as const;
