import {
  Banner,
  BlockStack,
  reactExtension,
  Text,
  useApi,
  useTranslate,
} from "@shopify/ui-extensions-react/checkout";

// AppApprove Checkout UI extension — replaces the placeholder example
// generated by the wizard. Gates on Shopify Plus targets via shop.plan
// before exercising any Plus-only API; without that gate the merchant
// gets a confusing runtime error on Standard plans and Shopify rejects
// the submission for "feature unavailable on declared plan".

export default reactExtension("purchase.checkout.block.render", () => <Extension />);

function Extension() {
  const translate = useTranslate();
  const { shop } = useApi();
  // shop.myshopifyDomain is always defined; shop.plan is undefined on
  // non-Plus stores. Treat undefined as "not Plus".
  const isPlusStore =
    typeof (shop as unknown as { plan?: { displayName?: string } }).plan?.displayName === "string" &&
    /plus/i.test((shop as unknown as { plan: { displayName: string } }).plan.displayName);

  return (
    <BlockStack spacing="base">
      <Banner status="info" title={translate("intro.title")}>
        <Text>{translate("intro.body")}</Text>
      </Banner>
      {isPlusStore ? (
        <Text>{translate("plus.body")}</Text>
      ) : (
        <Text>{translate("standard.body")}</Text>
      )}
    </BlockStack>
  );
}
